name: CPP-lint-ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        docker build -t my-cpp-app .
        docker run my-cpp-app cpplint *.cpp *.h
