name: CI - cpp Linter

on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y build-essential
      - name: Compile C++ 2017
        run: g++ GameDie.cpp main.cpp -std=c++17 -o roller
      - name: install cpplint
        run: apt-get update && \
            apt-get install -y \
            build-essential \
            g++ \
            cmake \
            git-all \
            dos2unix \
            python3 \
            python3-pip
        run: pip install cpplint
      - name: run linter
        run: cpplint *.cpp *.h