name: cpplint

on:
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -f build-essential g++ cmake git-all dos2unix python3 python3-pip
          pip install cpplint
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cpplint GameDie
        run: cpplint *.cpp *.h