name: CPPLint

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CPPLint
      run: |
        sudo apt-get install -y python3-pip
        pip3 install cpplint

    - name: Run CPPLint
      run: |
        cpplint --recursive --extensions=h,cpp ./
