name: Lint C++

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: docker build -t cpp-container .
      - name: Lint
        run: docker run -it cpp-container cpplint *.cpp *.h